In [1]:
###### Linear regression 
### lib (sklearn)

In [2]:
import pandas as pd 
import sklearn

In [3]:
df=pd.read_csv("USA_Housing.csv")

In [4]:
df.head()

,Avg. Area Income,Avg. Area House Age,Avg. Area Number of Rooms,Avg. Area Number of Bedrooms,Area Population,Price
0,79545.45857,5.682861,7.009188,4.09,23086.80050,1.059034e+06
1,79248.64245,6.002900,6.730821,3.09,40173.07217,1.505891e+06
2,61287.06718,5.865890,8.512727,5.13,36882.15940,1.058988e+06
3,63345.24005,7.188236,5.586729,3.26,34310.24283,1.260617e+06
4,59982.19723,5.040555,7.839388,4.23,26354.10947,6.309435e+05

In [5]:
x=df.drop("Price",axis=1)### FEATURES
y=df["Price"]### TARGET

In [6]:
x

,Avg. Area Income,Avg. Area House Age,Avg. Area Number of Rooms,Avg. Area Number of Bedrooms,Area Population
0,79545.45857,5.682861,7.009188,4.09,23086.80050
1,79248.64245,6.002900,6.730821,3.09,40173.07217
2,61287.06718,5.865890,8.512727,5.13,36882.15940
3,63345.24005,7.188236,5.586729,3.26,34310.24283
4,59982.19723,5.040555,7.839388,4.23,26354.10947
...,...,...,...,...,...
4995,60567.94414,7.830362,6.137356,3.46,22837.36103
4996,78491.27543,6.999135,6.576763,4.02,25616.11549
4997,63390.68689,7.250591,4.805081,2.13,33266.14549
4998,68001.33124,5.534388,7.130144,5.44,42625.62016
4999,65510.58180,5.992305,6.792336,4.07,46501.28380

In [7]:
y

0       1.059034e+06
1       1.505891e+06
2       1.058988e+06
3       1.260617e+06
4       6.309435e+05
            ...
4995    1.060194e+06
4996    1.482618e+06
4997    1.030730e+06
4998    1.198657e+06
4999    1.298950e+06
Name: Price, Length: 5000, dtype: float64

In [8]:
from sklearn.model_selection import train_test_split

In [9]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.33)

In [10]:
x_train

,Avg. Area Income,Avg. Area House Age,Avg. Area Number of Rooms,Avg. Area Number of Bedrooms,Area Population
3670,95603.92948,5.917745,7.387691,6.03,36505.44106
370,74449.12174,6.223626,7.392675,3.10,24837.59073
3465,45103.81573,5.716328,6.645191,2.10,43067.01157
3040,62671.73070,5.537927,6.402028,4.44,31702.71455
4120,70169.71055,6.227945,7.651813,3.36,35197.38496
...,...,...,...,...,...
4851,55899.51630,5.220085,5.164152,2.01,43063.50372
2144,64315.31047,6.478004,6.389381,2.10,34940.35476
3498,62135.39477,7.314557,6.468901,2.26,37575.23589
739,87314.63582,5.070006,6.684680,2.18,25224.64592
2690,82943.88907,6.021106,6.278453,4.25,50524.73674

In [11]:
x_test

,Avg. Area Income,Avg. Area House Age,Avg. Area Number of Rooms,Avg. Area Number of Bedrooms,Area Population
1619,60610.61064,4.019357,5.539636,4.09,49512.90932
636,54535.45372,5.278065,6.871038,4.41,30852.20701
2487,79687.76187,6.010368,7.337394,6.09,20867.66988
1314,68353.72575,5.184548,7.424004,5.41,27804.83013
229,91731.15438,5.184811,7.943880,6.30,33102.09542
...,...,...,...,...,...
3594,68335.72629,4.914224,6.703796,3.02,31341.62494
4773,53917.87223,3.824204,7.360602,4.33,44916.29140
4888,68789.32901,5.851196,8.258215,3.50,41491.22028
2109,72007.48880,5.745688,6.786491,2.13,53713.27621
1585,48879.09809,6.157261,8.040755,3.39,30730.40151

In [12]:
from sklearn.linear_model import LinearRegression

In [13]:
lr=LinearRegression()

In [14]:
model=lr.fit(x_train,y_train)

In [15]:
pred=model.predict(x_test)

/opt/anaconda3/envs/rag/lib/python3.10/site-packages/sklearn/linear_model/_base.py:280: RuntimeWarning: divide by zero encountered in matmul
  return X @ coef_ + self.intercept_
/opt/anaconda3/envs/rag/lib/python3.10/site-packages/sklearn/linear_model/_base.py:280: RuntimeWarning: overflow encountered in matmul
  return X @ coef_ + self.intercept_
/opt/anaconda3/envs/rag/lib/python3.10/site-packages/sklearn/linear_model/_base.py:280: RuntimeWarning: invalid value encountered in matmul
  return X @ coef_ + self.intercept_

In [16]:
pred

array([ 767244.28261236,  719413.12664495, 1292373.42689663, ...,
       1451295.22787886, 1509408.70265383,  879139.43059275],
      shape=(1650,))

In [17]:
from sklearn.metrics import r2_score ,mean_squared_error

In [18]:
print(r2_score(pred,y_test)**0.5)

0.9571147414036559

In [19]:
print(mean_squared_error(pred,y_test)**0.5)

99529.37513629594

In [20]:
###### POLYNOMIAL REG
from sklearn.preprocessing import PolynomialFeatures
poly=PolynomialFeatures(degree=3)

In [21]:
x_poly_train=poly.fit_transform(x_train)
x_poly_test=poly.fit_transform(x_test)

In [22]:
model=lr.fit(x_poly_train,y_train)

In [23]:
pred=model.predict(x_poly_test)

/opt/anaconda3/envs/rag/lib/python3.10/site-packages/sklearn/linear_model/_base.py:280: RuntimeWarning: divide by zero encountered in matmul
  return X @ coef_ + self.intercept_
/opt/anaconda3/envs/rag/lib/python3.10/site-packages/sklearn/linear_model/_base.py:280: RuntimeWarning: overflow encountered in matmul
  return X @ coef_ + self.intercept_
/opt/anaconda3/envs/rag/lib/python3.10/site-packages/sklearn/linear_model/_base.py:280: RuntimeWarning: invalid value encountered in matmul
  return X @ coef_ + self.intercept_

In [24]:
pred

array([ 775318.88616089,  720419.33865986, 1275003.75843211, ...,
       1446648.08604831, 1506753.04410441,  862687.24456463],
      shape=(1650,))

In [25]:
print(r2_score(pred,y_test)**0.5)
print(mean_squared_error(pred,y_test)**0.5)

0.9567613040297996
99836.78249302684

In [26]:
#### DECISION TREE REGRESSION 
from sklearn.tree import DecisionTreeRegressor

In [27]:
dt=DecisionTreeRegressor(max_depth=15)

In [28]:
model=dt.fit(x_train,y_train)

In [29]:
pred=model.predict(x_test)

In [30]:
pred

array([1019127.733 ,  623181.1348, 1335883.831 , ..., 1295967.387 ,
       1580951.579 ,  777733.6134], shape=(1650,))

In [31]:
print(r2_score(pred,y_test)**0.5)
print(mean_squared_error(pred,y_test)**0.5)

0.8630496635220309
176512.55451982698

In [32]:
###### K-Nearest Neignbor (KNN)

In [33]:
from sklearn.neighbors import KNeighborsRegressor

In [34]:
knn=KNeighborsRegressor(n_neighbors=6)

In [35]:
model=knn.fit(x_train,y_train)

In [36]:
pred=model.predict(x_test)

In [37]:
print(r2_score(pred,y_test)**0.5)
print(mean_squared_error(pred,y_test)**0.5)

0.3898639125353324
249534.34040783416

In [38]:
##### SUPPORT VECTOR MACHINES (SVRegressor)

In [39]:
from sklearn.svm import SVR

In [40]:
sv=SVR()

In [41]:
model=sv.fit(x_train,y_train)

In [42]:
pred=model.predict(x_test)

In [43]:
pred

array([1230439.94873827, 1230301.91460306, 1230451.7813449 , ...,
       1230466.92536527, 1230547.64926507, 1230264.81324144],
      shape=(1650,))

In [46]:
print(r2_score(pred,y_test)**10)
print(mean_squared_error(pred,y_test)**0.5)

7.854263762372507e+71
355709.12563965144